### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ntung** [flaxsearch/BioSolr#2]
java -jar swat4ls-webapp-1.0-SNAPSHOT.jar server webapp.yml
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/co/flax/biosolr/ontology/OntologyApplication : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by mattflax** [comment]
Hi,

Which Java version are you using? Both Solr 5 and the web application require Java 8 in order to run.

**Comment by ntung** [comment]
I am running under Java 7

**Comment by ntung** [comment]
You are right, @mattflax. I resolved this issue.
The issue is closed too.
